accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import signup_form


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup_form, name="signup"),

]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    ExpenseCategoryCreateView,
    AccountListView,
    AccountCreateView
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories"
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path("accounts/", AccountListView.as_view(), name="list_account"),
    path(
        "accounts/create/",
        AccountCreateView.as_view(),
        name="create_account",
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        User,
        related_name="categories",
        on_delete=models.CASCADE,
        null=True
        )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        User,
        related_name="accounts",
        on_delete=models.CASCADE
        )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField(default=timezone.now)
    purchaser = models.ForeignKey(
        User,
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True
        )
    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE
        )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True
    )

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.


def signup_form(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = User.objects.create_user(
                username=username,
                password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from receipts.models import Receipt, ExpenseCategory, Account
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    context_object_name = "receipt"
    template_name = "receipts/list.html"

    def get_queryset(self):
        context = Receipt.objects.filter(purchaser=self.request.user)
        return context


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.user_property = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/expense_categories.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/accounts.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/create_category.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/create_account.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_account")

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Expenses: the Web App!</title>

</head>

<body>
  <header>
    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li>
            <a href="{% url 'logout' %}">Logout</a>
          </li>
          <li>
            <a href="{% url 'list_categories' %}">Categories</a>
          </li>
          <li>
            <a href="{% url 'create_category' %}">Create Category</a>
          </li>
          <li>
            <a href="{% url 'list_account' %}">Accounts</a>
          </li>
          <li>
            <a href="{% url 'create_account' %}">Create Account</a>
          </li>
          <li>
            <a href="{% url 'home' %}">Receipts</a>
          </li>
          <li>
            <a href="{% url 'create_receipt' %}">Create Receipt</a>
          </li>
          {% endif %} {% if user.is_anonymous %}
          <li>
            <a href="{% url 'signup' %}">Sign Up</a>
          </li>
          <li>
            <a href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
      </ul>
    </nav>
    {% block pagination %}
    {% endblock pagination %}
  </header>
  {% block content %}
  {% endblock content %}
</body>

</html>

receipts/templates/receipts/accounts.html
{% extends "../base.html" %}

{% block content %}
  <main>
        <h1>My Accounts</h1>
        <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of receipts</th>
              </tr>
            </thead>
            <tbody>
              {% for account in account_list %}
                <tr>
                  <td> {{ account.name }} </td>
                  <td> {{ account.number }} </td>
                  <td> {{ account|length }} </td>
                </tr>
            </tbody>
            {% endfor %}
          </table>
  </main>
  {% endblock content %}

receipts/templates/receipts/create.html
{% extends "../base.html" %}
{% block content %}
<main>
    <div>
    <h1>Create Receipt</h1>
    <form method="post">
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
    </div>
</main>
{% endblock content %}

receipts/templates/receipts/create_account.html
{% extends "../base.html" %}
{% block content %}
<main>
    <div>
    <h1>Create Account</h1>
    <form method="post">
         {% csrf_token %} {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
    </div>
</main>
{% endblock content %}

receipts/templates/receipts/create_category.html
{% extends "base.html" %}
{% block content %}
<main>
	<div>
	  <h1>Create Category</h1>
	  <form method="post">
	    {% csrf_token %} {{ form.as_p }}
    	<button type="submit">Create</button>
	  </form>
	</div>
</main>
{% endblock content %}

receipts/templates/receipts/expense_categories.html
{% extends "../base.html" %}

{% block content %}
  <main>
        <h1>My Categories</h1>
        <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Number of receipts</th>
              </tr>
            </thead>
            <tbody>
              {% for category in expensecategory_list %}
                <tr>
                  <td> {{ category.name }} </td>
                  <td> {{ category.receipts.all | length }} </td>
                </tr>
            </tbody>
            {% endfor %}
          </table>
  </main>
  {% endblock content %}

receipts/templates/receipts/list.html
{% extends "../base.html" %}

{% block content %}
  <main>
        <h1>My Receipts</h1>
        <table>
            <thead>
              <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
              </tr>
            </thead>
            <tbody>
              {% for receipt in receipt %}
                <tr>
                  <td> {{ receipt.vendor }} </td>
                  <td> {{ receipt.total }} </td>
                  <td> {{ receipt.tax }} </td>
                  <td> {{ receipt.date|date:'m-d-Y' }} </td>
                  <td> {{ receipt.category }} </td>
                  <td> {{ receipt.account }} </td>
                </tr>
              {% endfor %}
            </tbody>
        </table>
  </main>
{% endblock content %}